AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SDK Layer

Resources:
  SDKlayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWS-SDK-v3_289
      Description: AWS SDK 3.289.0
      ContentUri: ./layer
      CompatibleRuntimes:
        - nodejs16.x
        - nodejs18.x
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
    
